### ISSUE TITLE
Question: What does 'Coverage' in the total C/N/S cycles mean?

### ISSUE THREAD

**Issue by susheelbhanu** [AnantharamanLab/METABOLIC#34]
Hi all, 

Just a quick question regarding the `coverage` value in the `draw_carbon_cycle_total.pdf` plots. 

For example, I have the attached output which shows that `583 genomes` are involved in `Organic Carbon Oxidation` with a coverage of `~45.1%`. 

What does `coverage` here represent and how is it calculated, especially in the context of the 583 genomes?

Thank you very much for your help!
[draw_carbon_cycle_total.pdf](https://github.com/AnantharamanLab/METABOLIC/files/6096871/draw_carbon_cycle_total.pdf)

**Comment by patriciatran** [comment]
Hi, the coverage in this plot refers the sum of the average coverage of the MAGs (genome-level) (not of set of genes only genes) predicted to be involved in that process. For example, if there are 3 organisms involved in carbon oxidation, and from the mapping step it was inferred that Organisms A has 2% coverage, B has 5%, and C has 6% in the reads set you gave METABOLIC, then the "coverage value" for carbon oxidation would be 2+5+6 = 13%. You can think of coverage here as the relative "abundance" of the organisms compared to the "abundance" of all MAGS in that sample.

**Comment by susheelbhanu** [comment]
Thank you @patriciatran! So, this doesn't mean that 45.1% of the genomes have these set of genes, right?!

Rather out of a possible 100% coverage across all genomes, this pathway has 45% coverage?

Sorry for the redundant questions, but just trying to understand the implications of this value.

**Comment by patriciatran** [comment]
Hi @susheelbhanu , yes you are correct that _**it does not**_ mean that 45.1% of genomes have these genes. To know how many of your MAGS have that process, you would just take 531 MAGS divided by total number of MAGS in your original fasta folder. 

**Yes**, you are correct: this would be out the maximum possible values would be 100% since in my example above the 2%, 5% and 6% are already calculated as abundance out of the total number of reads (reads mapped divided by total number of reads X 100 = % value). You can interpret it (in your attached PDF) as: you have 531 MAGS that could potentially perform carbon oxidation, and that they correspond to 45.1% "relative abundance" in your sample.

**Comment by susheelbhanu** [comment]
Awesome, thank you very much for the detailed explanation.

**Comment by ChaoLab** [comment]
Yes. "num" here means the num of MAGs that have the function. "coverage" means the relative coverage of these MAGs within the total microbial community. They are different. The extreme condition would be that there is only one genome in 100 genomes to have this function, while, this genome has very high coverage (like, 95%). This situation could be interpreted as this genome is the major contributor to this function in the microbial community, unproportionally high to its genome num percentage in the microbial community.
