### ISSUE TITLE
Possible to concatenate Hmm files ?

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/METABOLIC#4]
Hi,
The software creates ~10,000 hmm files per genome, I tried to run the analysis on ~100 of them which created thus ~100,000 files that the cluster that I'm using is finding quite hard to process. I would suggest if possible to concatenate all these to have 1 per genome if possible?
Best
Gregoire

**Comment by ChaoLab** [comment]
The reason that we created individual result files for hmmsearch is that you could re-check the initial hmmsearch results.

Our primary result of hmmsearch is based on Kofam database, which only provides separated hmm files. The other issue is that, to make the hmmsearch result stringent, for each hmm file, we will use different cut-off values.

Since that you use cluster, do you have problems to write down and read those files?

**Comment by michoug** [comment]
Hi, yes the cluster is having a lot of difficulties reading/writing more than 50k files in one folder.
May I suggest if possible to create a different folder for each MAG to avoid such a high number of files?

**Comment by ChaoLab** [comment]
Many thanks! A good suggestion. I will try to update it.

**Comment by ChaoLab** [comment]
Hi, michoug,
Many thanks for your suggestion to improve the software. I have updated the script accordingly in our new versions.
