### ISSUE TITLE
What happens with several reads pairs?

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/METABOLIC#50]
Hi,
Something that I don't find very clear in the documentation, is what happens to the "figures" if there are several reads pairs.
I wanted to compared metagenomic samples to check the differences in metabolism/MAGs abundance after a coassembly.
If I have 5 samples, should I run the script 5 times with one sample each time?  Such as for example to obtain different MW-scores for each samples.
Thanks!
Greg

**Comment by patriciatran** [comment]
Hi Greg,

If you have 5 samples and you want to compare amongst them, run metabolic-c
t times as to get 5 times the plots.

If you have 1 sample that you have MAGS made from and without assembly, and
you want to compare if using the coassembly affects the metabolic pathways
in your MAGs, that is as if you had '2 conditions' to compare, so youd run
metabolic 2 times.

Similarly, if for example you have 5 conditions/treatments and each
treatment has 3 replications, you could run metabolic-g 5 times (for each
treatment, but give it the 3 read set of each rep wihin that condition).
That would alllow to compare between condition.

Does that answer your question? I might try to make a conceptual figure to
add to the doccumentation since that's probably a scenario others would
want to know to.

Let me know, thanks!

Patricia

**Comment by michoug** [comment]
Hi Patricia,
Thanks for the info.
I would then suggest, if possible, for the possibility to reuse annotations results (METABOLIC-G, I suppose) which would strongly decrease the overall runtime
Best
Greg

**Comment by ChaoLab** [comment]
Hi Greg,
Many thanks for your suggestions. we fully understand your requirement. We will work on this soon

**Comment by ChaoLab** [comment]
Hi Greg,
We developed an additional script based on your suggestion. You might want to have a check here: https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage/_edit#a-2nd-metabolic-c-run

**Comment by michoug** [comment]
Thanks!!
Will check it soon
