### ISSUE TITLE
A question about community analyses

### ISSUE THREAD

**Issue by Erique29** [AnantharamanLab/METABOLIC#53]
Hi,
  If I have 100 genomes of isolates, how can I run community analyses like metagenome genomes? Thanks!
Best wishes!

**Comment by patriciatran** [comment]
Hi Enrique,

If you have a FASTA file for each of your 100 isolates, put those .fasta
files in one folder and use that as the input folder.

Best,

Patricia

**Comment by Erique29** [comment]
Hi Patricia
I don't  know how to fill the -r flag, because I do not have metagenomic read datasets. Can you tell me? Thanks!
Best wishes,
Erique

**Comment by patriciatran** [comment]
Hi Enrique,

If you don't have read then you won't be able to do the METABOLIC-c
analysis, since the point of this analysis is to get an idea of how
abundant certain genes/processes/cycles are in your genomes, using the
reads from where they were sequenced (or elsewhere). If you want to
annotate each of your genomes using METABOLIC, use *METABOLIC-g.pl*, and
you will get a table summarizing all the annotations for your 100 genomes,
and get 1 plot per genome showing their individual involvement in C, N, S
and other cycles. (400 plots in total 4 * 100 genomes).

Let me know if you have any other questions! thanks.

Patricia

**Comment by Erique29** [comment]
Hi Patricia,  
Thanks! I got it. I will try it again after metagenomic sequencing.
Erique
