### ISSUE TITLE
Reads not mapping to metagenomes

### ISSUE THREAD

**Issue by TJrogers86** [AnantharamanLab/METABOLIC#58]
**Describe the bug**
I have 40 metagenomes from geothermal systems of which I assembled and binned seperately. From these, I produced 1,540 MAGs. The output of METABOLIC-C shows predicted pathways of each of the MAGs, but no read percent is given. 

**To Reproduce**
I believe it is more user error than a bug. My input commands are as follows:
perl METABOLIC-C.pl -t 40 -m-cutoff 0.60 -in-gn /home/lloydlab/TJ_BMS/Panama_2018_BMS/ALL_METAW_REFINED_BINS -kofam-db full -r /home/lloydlab/TJ_BMS/Panama_2018_BMS/Panama_Reads.txt -o Panama_Metabolic_Run -tax family

My .txt doc is as follows:
![image](https://user-images.githubusercontent.com/48442658/144651872-72d0f029-aa5d-4311-a1f0-ae85f245aeda.png)

MAG directory looks like this(not all fasta files would fit on screen):
![image](https://user-images.githubusercontent.com/48442658/144652157-a778744f-b1c3-4bfc-a861-85fac9dcb602.png)

Read directory looks like this:
![image](https://user-images.githubusercontent.com/48442658/144652239-3a8f864a-1262-4a79-bed3-bbfbcc4b3f12.png)

Some of the output files:
![image](https://user-images.githubusercontent.com/48442658/144652368-0fc96886-5433-492a-8b17-a5a4a5ab2fb3.png)
![image](https://user-images.githubusercontent.com/48442658/144652422-34120d14-240d-4870-ac15-32592f3bfaef.png)

When I only run MAGs and reads from two different Metagenomes, everything seems to work fine. But, once all are included, I get the above out put. Have I missed something? Any help will be greatly appreciated.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal
**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChaoLab** [comment]
@TJrogers86 Thank you for your comprehensive description of the issue. It seems like your reads mapping has a problem when processing the whole 40 metagenomic reads. Since you said it is OK for running two metagenomes. I guess it might be due to some limitations of your server. While I am not sure. Can you paste the log file to me (the standard-out printed on the screen when running METABOLIC-C)?

**Comment by TJrogers86** [comment]
Sorry for the delay. This is the output from the file marked METABOLIC_run.log. But i think you want me to run it again and send a screen shot of the output to the terminal screen, correct? If so, itll take a couple days to run and Ill upload a screen shot then. Thanks for your help!
![image](https://user-images.githubusercontent.com/48442658/147126564-e5064be0-d3b4-4b5e-9b50-e99dd8c92275.png)

**Comment by TJrogers86** [comment]
> @TJrogers86 Thank you for your comprehensive description of the issue. It seems like your reads mapping has a problem when processing the whole 40 metagenomic reads. Since you said it is OK for running two metagenomes. I guess it might be due to some limitations of your server. While I am not sure. Can you paste the log file to me (the standard-out printed on the screen when running METABOLIC-C)?

Here is the print out after the run:
![image](https://user-images.githubusercontent.com/48442658/147489407-7ba85242-fbff-4769-9417-0915ba8ee37e.png)

**Comment by ChaoLab** [comment]
@TJrogers86 
For the "No such file or directory: 'temp'" error, I think it is the same with the error in https://github.com/AnantharamanLab/METABOLIC/issues/26. Here I attached the file to you (delete the ".txt" to use): [hmmscan-parser-dbCANmeta.py.txt](https://github.com/AnantharamanLab/METABOLIC/files/7787064/hmmscan-parser-dbCANmeta.py.txt)

For the error reports of "Saw ASCII character 10 but expected 33-based Phred qual", I think it is due to the format of your input reads, see this link: https://www.biostars.org/p/377566/

**Comment by TJrogers86** [comment]
Sorry, I ment to update you. Making the file change (hmmscan-parser-dbCANmeta.py.txt) fixed the issue. Thanks so much for your help and sorry it took so long to update you.
